Repository HE-Arc/TimeLife, pull requests merged in 2021-12, with the labels that each got.

#27 feat(#10): Gallery View
  app/Http/Controllers/AlbumController.php
  resources/js/Component/CardPicture.vue
  resources/js/Component/Menu.vue
  resources/js/Pages/Gallery.vue
  resources/scss/app.scss
  routes/web.php
Labels: Frontend

#28 feat(#5): User log in and log out
  app/Http/Controllers/UserController.php
  app/Models/User.php
  resources/js/Component/Menu.vue
  resources/js/Pages/Home.vue
  resources/js/Pages/Profil.vue
  resources/js/Pages/SignUp.vue
  routes/web.php
Labels: Backend

#30 fix(#29): mixed content
  app/Providers/AppServiceProvider.php
Labels: bug, Backend, Deploy

#33 feat(#15): Upload modal
  app/Http/Controllers/PhotoController.php
  resources/js/Component/UploadModal.vue
  resources/js/Pages/Gallery.vue
  resources/js/app.js
  resources/scss/app.scss
  resources/views/app.blade.php
  routes/web.php
Labels: Frontend

#34 feat(#31): create-album view
  app/Http/Controllers/AlbumController.php
  resources/js/Component/CreateModal.vue
  resources/js/Pages/CreateAlbum.vue
  routes/web.php
Labels: Frontend

#39 feat(#26): Upload and validate pictures on the server
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/PhotoController.php
  app/Http/Kernel.php
  app/Http/Middleware/HandleInertiaRequests.php
  config/filesystems.php
  resources/js/Component/UploadModal.vue
  resources/js/Pages/Gallery.vue
  routes/web.php
Labels: Backend, Frontend
