Repository HE-Arc/TimeLife, pull requests merged in 2022-01, with the labels that each got.

#37 feat(#35): Album List View
  app/Http/Controllers/AlbumController.php
  resources/js/Component/CardAlbum.vue
  resources/js/Pages/Album.vue
  routes/web.php
Labels: Frontend

#36 feat(#32): Add message signup and login
  app/Http/Controllers/UserController.php
  app/Http/Middleware/HandleInertiaRequests.php
  resources/js/Pages/Home.vue
  resources/js/Pages/Login.vue
  resources/js/Pages/SignUp.vue
  resources/scss/app.scss
  routes/web.php
Labels: Backend, Frontend

#38 feat(#12): Profile view
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/UserController.php
  resources/js/Component/Menu.vue
  resources/js/Pages/Profil.vue
  resources/js/Pages/Profile.vue
  routes/web.php
Labels: Frontend

#44 feat(#43): Handle request
  app/Http/Controllers/StorageController.php
  routes/web.php
Labels: Backend

#46 feat(#42): Album Thumbnail
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/UserController.php
  resources/js/Pages/Album.vue
  routes/web.php
Labels: Frontend

#52 feat(#47): Albums links
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/UserController.php
  app/Http/Services/ThumbnailService.php
  resources/js/Component/CardAlbum.vue
  resources/js/Pages/Album.vue
  resources/js/Pages/Profile.vue
Labels: Frontend

#51 feat(#17): Create timeline view
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/StorageController.php
  resources/js/Component/Timeline/Bar.vue
  resources/js/Component/Timeline/TimelineEvent.vue
  resources/js/Pages/Timeline.vue
  resources/js/app.js
  routes/web.php
Labels: Backend, Frontend

#57 feat(#56): display user picture with gravatar
  app/Http/Controllers/UserController.php
  resources/js/Pages/Profile.vue
Labels: Frontend

#55 feat(#54): display real pictures in gallery
  app/Http/Controllers/AlbumController.php
  resources/js/Component/CardPicture.vue
  resources/js/Pages/Gallery.vue
Labels: Frontend

#60 feat(#58): Cleaning route and user
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/PhotoController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/HandleInertiaRequests.php
  resources/js/Component/Menu.vue
  resources/js/Pages/Album.vue
  resources/js/Pages/Profile.vue
  resources/js/Pages/UpdateUser.vue
  routes/web.php
Labels: Backend

#64 feat: Simple permission
  app/Http/Controllers/AlbumController.php
  app/Http/Controllers/UserController.php
  app/Http/Kernel.php
  app/Http/Middleware/EnsureAlbumPermission.php
  resources/js/Pages/Gallery.vue
  routes/web.php
Labels: Backend, Frontend

#63 feat(#61): Side menu for gallery and timeline
  resources/js/Pages/Gallery.vue
  resources/js/Pages/Timeline.vue
Labels: Frontend
